### ISSUE TITLE
Building a reference set troubleshooting

### ISSUE THREAD

**Issue by dfeistel3** [baymlab/wastewater_analysis#2]
thanks for the last issue solution!

some new issues i have run into:

1. calling non-ambiguous characters character:  
the first command using `sed`, the output file is only a single column numbered list.  But the code in `preprocess_references.py` under the function add_nonN_count() looks like the input file needs two columns (id, count) for the dictionary.  should this file have the first column with 'id' and second with 'count' or did i miss some something in the code that take care of that?  Here is the error:

Traceback (most recent call last):
  File "../pipeline/preprocess_references.py", line 144, in <module>
    sys.exit(main())
  File "../pipeline/preprocess_references.py", line 30, in main
    metadata_df = read_metadata(args.metadata, args.nonN_counts)
  File "../pipeline/preprocess_references.py", line 117, in read_metadata
    df = add_nonN_count(df, nonN_count_file)
  File "../pipeline/preprocess_references.py", line 135, in add_nonN_count
    id, count = line.rstrip('\n').split('\t')
ValueError: not enough values to unpack (expected 2, got 1)

2. `preprocess_references.py` and the metafile
Has the metadata column headers changed since you originally downloaded it from GISAID on March 9? Some of the strings that are searched in the data frame (e.g. pango_lineage & country; lines 46 & 48 respectively) are not listed as such in the recent GISAID metafile I downloaded on September 16th.  Any insight?

**Comment by jbaaijens** [comment]
Hi @dfeistel3, I just downloaded the most recent metadata and indeed, the format has changed quite a bit. The good news is that the metadata now includes columns specifying N-content and completeness, which means that we can skip the first step of counting non-N characters. I will update the script `preprocess_references.py` to allow working with the latest GISAID metadata.
